/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsx createPlasmicElementProxy */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eygJxeRspPrtKABTYb2Jd2
// Component: iTUWmT1Up8N
import * as React from "react";
import {
  hasVariant,
  classNames,
  Flex,
  wrapWithClassName,
  Renderer,
  NodeRenderer,
  createPlasmicElementProxy,
  makeFragment,
  PlasmicIcon,
  PlasmicSlot,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_brenorocha_dev.css"; // plasmic-import: eygJxeRspPrtKABTYb2Jd2/projectcss
import "./PlasmicFooterWrapper.css"; // plasmic-import: iTUWmT1Up8N/css
import IconIcon from "./PlasmicIcon__Icon"; // plasmic-import: apFMqbzLSD/icon
import Vector5Icon from "./PlasmicIcon__Vector5"; // plasmic-import: ANOo1lWgFbR/icon
import Icon3Icon from "./PlasmicIcon__Icon3"; // plasmic-import: QpIW3BixvU/icon

export type PlasmicFooterWrapper__VariantMembers = {};
export type PlasmicFooterWrapper__VariantsArgs = {};
export const PlasmicFooterWrapper__VariantProps = new Array<
  keyof PlasmicFooterWrapper__VariantsArgs
>();

export type PlasmicFooterWrapper__ArgsType = {};
export const PlasmicFooterWrapper__ArgProps = new Array<
  keyof PlasmicFooterWrapper__ArgsType
>();

export type PlasmicFooterWrapper__OverridesType = {
  root?: Flex<"div">;
  contactInfo?: Flex<"div">;
  linkedIn?: Flex<"a">;
  linkedin?: Flex<"div">;
  gitHub?: Flex<"a">;
  github?: Flex<"div">;
  gmail?: Flex<"div">;
  link?: Flex<"a">;
  img?: Flex<"img">;
};

export interface DefaultFooterWrapperProps {
  className?: string;
}

function PlasmicFooterWrapper__RenderFunc(props: {
  variants: PlasmicFooterWrapper__VariantsArgs;
  args: PlasmicFooterWrapper__ArgsType;
  overrides: PlasmicFooterWrapper__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames({
        FooterWrapper__root__suN0W: true,
        "plasmic-default__all": true,
        "plasmic-default__div": true
      })}
    >
      <div
        data-plasmic-name={"contactInfo"}
        data-plasmic-override={overrides.contactInfo}
        className={classNames({
          FooterWrapper__contactInfo__bygtW: true,
          "plasmic-default__all": true,
          "plasmic-default__div": true
        })}
      >
        <div
          className={
            classNames({
              FooterWrapper__box___mx7u: true,
              "plasmic-default__all": true,
              "plasmic-default__div": true
            }) + " __wab_text"
          }
        >
          {"// CONTACT"}
        </div>

        <div
          className={
            classNames({
              FooterWrapper__box__B9f0w: true,
              "plasmic-default__all": true,
              "plasmic-default__div": true
            }) + " __wab_text"
          }
        >
          {"get in touch"}
        </div>

        <div
          className={
            classNames({
              FooterWrapper__box__3AhBk: true,
              "plasmic-default__all": true,
              "plasmic-default__div": true
            }) + " __wab_text"
          }
        >
          {"------------------------------------"}
        </div>

        <a
          data-plasmic-name={"linkedIn"}
          data-plasmic-override={overrides.linkedIn}
          className={classNames({
            FooterWrapper__linkedIn__9x2On: true,
            "plasmic-default__a": true,
            "plasmic-default__all": true
          })}
          href={"https://www.linkedin.com/in/breno-rocha-dev/" as const}
          title={"wanna hire me? let's talk" as const}
        >
          <div
            className={
              classNames({
                FooterWrapper__box__4ZRbu: true,
                "plasmic-default__all": true,
                "plasmic-default__div": true
              }) +
              " " +
              ("linkedin" as const) +
              " __wab_text"
            }
          >
            {"linkedin/breno-rocha-dev"}
          </div>

          <div
            data-plasmic-name={"linkedin"}
            data-plasmic-override={overrides.linkedin}
            className={classNames({
              FooterWrapper__linkedin__ITuen: true,
              "plasmic-default__all": true,
              "plasmic-default__div": true
            })}
          ></div>
        </a>

        <a
          data-plasmic-name={"gitHub"}
          data-plasmic-override={overrides.gitHub}
          className={classNames({
            "FooterWrapper__gitHub__-Hyiu": true,
            "plasmic-default__a": true,
            "plasmic-default__all": true
          })}
          href={"https://github.com/git-BR" as const}
          title={"wanna hire me? let's talk" as const}
        >
          <div
            className={
              classNames({
                FooterWrapper__box__fy2wx: true,
                "plasmic-default__all": true,
                "plasmic-default__div": true
              }) +
              " " +
              ("github" as const) +
              " __wab_text"
            }
          >
            {"github.com/git-BR"}
          </div>

          <div
            data-plasmic-name={"github"}
            data-plasmic-override={overrides.github}
            className={classNames({
              FooterWrapper__github__4uo5G: true,
              "plasmic-default__all": true,
              "plasmic-default__div": true
            })}
          >
            <IconIcon
              className={classNames({
                FooterWrapper__svg__0Gx1i: true,
                "plasmic-default__all": true,
                "plasmic-default__svg": true
              })}
              role={"img"}
              {...({} as any)}
            ></IconIcon>
          </div>
        </a>

        <a
          className={classNames({
            FooterWrapper__link__WJiau: true,
            "plasmic-default__a": true,
            "plasmic-default__all": true
          })}
          href={"https://twitter.com/BrenoRocha_twt" as const}
          title={"wanna hire me? let's talk" as const}
        >
          <div
            className={
              classNames({
                FooterWrapper__box__bM5Tr: true,
                "plasmic-default__all": true,
                "plasmic-default__div": true
              }) +
              " " +
              ("twitter" as const) +
              " __wab_text"
            }
          >
            {"@BrenoRocha_twt"}
          </div>

          <div
            className={classNames({
              FooterWrapper__box__iihNK: true,
              "plasmic-default__all": true,
              "plasmic-default__div": true
            })}
          >
            <Vector5Icon
              className={classNames({
                FooterWrapper__svg__rGrHb: true,
                "plasmic-default__all": true,
                "plasmic-default__svg": true
              })}
              role={"img"}
              {...({} as any)}
            ></Vector5Icon>
          </div>
        </a>

        <a
          className={classNames({
            FooterWrapper__link__X1fE4: true,
            "plasmic-default__a": true,
            "plasmic-default__all": true
          })}
          href={"https://www.instagram.com/brenoh_rocha/" as const}
          title={"wanna hire me? let's talk" as const}
        >
          <div
            className={
              classNames({
                FooterWrapper__box__GKOTD: true,
                "plasmic-default__all": true,
                "plasmic-default__div": true
              }) +
              " " +
              ("instagram" as const) +
              " __wab_text"
            }
          >
            {"@brenoh_rocha"}
          </div>

          <Icon3Icon
            className={classNames({
              FooterWrapper__svg__9WmT5: true,
              "plasmic-default__all": true,
              "plasmic-default__svg": true
            })}
            role={"img"}
            {...({} as any)}
          ></Icon3Icon>

          <div
            className={classNames({
              FooterWrapper__box__dKcwO: true,
              "plasmic-default__all": true,
              "plasmic-default__div": true
            })}
          ></div>
        </a>

        <div
          data-plasmic-name={"gmail"}
          data-plasmic-override={overrides.gmail}
          className={classNames({
            FooterWrapper__gmail__CGT5n: true,
            "plasmic-default__all": true,
            "plasmic-default__div": true
          })}
          title={"wanna hire me? let's talk" as const}
        >
          <a
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            className={
              classNames({
                FooterWrapper__link__7vCcb: true,
                "plasmic-default__a": true,
                "plasmic-default__all": true
              }) +
              " " +
              ("email" as const) +
              " __wab_text"
            }
            href={"mailto:bhrochamail@gmail.com" as const}
          >
            {"bhrochamail@gmail.com"}
          </a>

          <img
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames({
              "FooterWrapper__img__-NgjZ": true,
              "plasmic-default__all": true,
              "plasmic-default__img": true
            })}
            role={"img"}
            src={
              "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNiAxNiI+CiAgPHBhdGggZD0iTTEyLjkgMTIuN0g1LjFjLTEgMC0yLjcuMy0zLjItLjgtLjItLjQtLjEtMS0uMS0xLjVWNS44YzAtLjYtLjEtMS4yLjQtMS42LjctLjcgMi4zLS40IDMuMi0uNGg2LjljLjQgMCAuOCAwIDEuMS4xLjkuMy45IDEuMi45IDJ2NWMtLjEuOS0uMyAxLjgtMS40IDEuOC0uNSAwLS41LjggMCAuNyAxLjEtLjEgMi0uOCAyLjEtMS45LjEtLjUgMC0xIDAtMS42VjUuMmMwLS45LS41LTEuNy0xLjMtMi0uNS0uMi0uOS0uMi0xLjQtLjJIMy4yYy0uOCAwLTEuNi40LTIgMS4yQzEgNC44IDEgNS40IDEgNnY1YzAgMS41LjggMi41IDIuNCAyLjVoOS41Yy40IDAgLjQtLjggMC0uOHoiIGZpbGw9IiNlYjM0M2MiLz4KICA8cGF0aCBkPSJNMS4yIDUuNWw2LjYgNC44Yy4xLjEuMy4xLjQgMGw2LjYtNC44Yy40LS4zIDAtLjktLjQtLjYtMi4yIDEuNi00LjQgMy4yLTYuNiA0LjdoLjRDNiA4LjEgMy44IDYuNSAxLjYgNC45Yy0uNC0uMy0uOC4zLS40LjZ6IiBmaWxsPSIjZWIzNDNjIi8+CiAgPHBhdGggZD0iTTEuNiAxMS44YzEuNC0xIDIuOS0yLjEgNC4zLTMuMS40LS4zIDAtLjktLjQtLjYtMS40IDEtMi45IDIuMS00LjMgMy4xLS40LjMgMCAuOS40LjZ6bTEzLS42Yy0xLjQtMS0yLjktMi4xLTQuMy0zLjEtLjQtLjMtLjguNC0uNC42IDEuNCAxIDIuOSAyLjEgNC4zIDMuMS40LjMuOC0uMy40LS42eiIgZmlsbD0iI2ViMzQzYyIvPgo8L3N2Zz4K" as const
            }
          ></img>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

class PlasmicFooterWrapper__Renderer extends Renderer<
  PlasmicFooterWrapper__VariantsArgs,
  PlasmicFooterWrapper__ArgsType,
  PlasmicFooterWrapper__OverridesType,
  "root"
> {
  constructor(
    variants: PlasmicFooterWrapper__VariantsArgs,
    args: PlasmicFooterWrapper__ArgsType
  ) {
    super(variants, args, PlasmicFooterWrapper__RenderFunc, "root");
  }

  protected create(
    variants: PlasmicFooterWrapper__VariantsArgs,
    args: PlasmicFooterWrapper__ArgsType
  ) {
    return new PlasmicFooterWrapper__Renderer(variants, args);
  }

  getInternalVariantProps(): (keyof PlasmicFooterWrapper__VariantsArgs)[] {
    return PlasmicFooterWrapper__VariantProps;
  }

  getInternalArgProps(): (keyof PlasmicFooterWrapper__ArgsType)[] {
    return PlasmicFooterWrapper__ArgProps;
  }

  forNode(
    name: "img"
  ): NodeRenderer<
    PlasmicFooterWrapper__VariantsArgs,
    PlasmicFooterWrapper__ArgsType,
    {
      img?: Flex<"img">;
    }
  >;

  forNode(
    name: "link"
  ): NodeRenderer<
    PlasmicFooterWrapper__VariantsArgs,
    PlasmicFooterWrapper__ArgsType,
    {
      link?: Flex<"a">;
    }
  >;

  forNode(
    name: "gmail"
  ): NodeRenderer<
    PlasmicFooterWrapper__VariantsArgs,
    PlasmicFooterWrapper__ArgsType,
    {
      gmail?: Flex<"div">;
      link?: Flex<"a">;
      img?: Flex<"img">;
    }
  >;

  forNode(
    name: "github"
  ): NodeRenderer<
    PlasmicFooterWrapper__VariantsArgs,
    PlasmicFooterWrapper__ArgsType,
    {
      github?: Flex<"div">;
    }
  >;

  forNode(
    name: "gitHub"
  ): NodeRenderer<
    PlasmicFooterWrapper__VariantsArgs,
    PlasmicFooterWrapper__ArgsType,
    {
      gitHub?: Flex<"a">;
      github?: Flex<"div">;
    }
  >;

  forNode(
    name: "linkedin"
  ): NodeRenderer<
    PlasmicFooterWrapper__VariantsArgs,
    PlasmicFooterWrapper__ArgsType,
    {
      linkedin?: Flex<"div">;
    }
  >;

  forNode(
    name: "linkedIn"
  ): NodeRenderer<
    PlasmicFooterWrapper__VariantsArgs,
    PlasmicFooterWrapper__ArgsType,
    {
      linkedIn?: Flex<"a">;
      linkedin?: Flex<"div">;
    }
  >;

  forNode(
    name: "contactInfo"
  ): NodeRenderer<
    PlasmicFooterWrapper__VariantsArgs,
    PlasmicFooterWrapper__ArgsType,
    {
      contactInfo?: Flex<"div">;
      linkedIn?: Flex<"a">;
      linkedin?: Flex<"div">;
      gitHub?: Flex<"a">;
      github?: Flex<"div">;
      gmail?: Flex<"div">;
      link?: Flex<"a">;
      img?: Flex<"img">;
    }
  >;

  forNode(
    name: "root"
  ): NodeRenderer<
    PlasmicFooterWrapper__VariantsArgs,
    PlasmicFooterWrapper__ArgsType,
    {
      root?: Flex<"div">;
      contactInfo?: Flex<"div">;
      linkedIn?: Flex<"a">;
      linkedin?: Flex<"div">;
      gitHub?: Flex<"a">;
      github?: Flex<"div">;
      gmail?: Flex<"div">;
      link?: Flex<"a">;
      img?: Flex<"img">;
    }
  >;

  forNode(name: keyof PlasmicFooterWrapper__OverridesType) {
    return super.forNode(name);
  }
}

type PlasmicFooterWrapperRootProps = PlasmicFooterWrapper__VariantsArgs &
  PlasmicFooterWrapper__ArgsType & {
    variants?: PlasmicFooterWrapper__VariantsArgs;
    args?: PlasmicFooterWrapper__ArgsType;
    overrides?: {
      root?: Flex<"div">;
      contactInfo?: Flex<"div">;
      linkedIn?: Flex<"a">;
      linkedin?: Flex<"div">;
      gitHub?: Flex<"a">;
      github?: Flex<"div">;
      gmail?: Flex<"div">;
      link?: Flex<"a">;
      img?: Flex<"img">;
    };

    root?: Flex<"div">;
    contactInfo?: Flex<"div">;
    linkedIn?: Flex<"a">;
    linkedin?: Flex<"div">;
    gitHub?: Flex<"a">;
    github?: Flex<"div">;
    gmail?: Flex<"div">;
    link?: Flex<"a">;
    img?: Flex<"img">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicFooterWrapper__VariantsArgs
    | keyof PlasmicFooterWrapper__ArgsType
    | "variants"
    | "args"
    | "root"
    | "contactInfo"
    | "linkedIn"
    | "linkedin"
    | "gitHub"
    | "github"
    | "gmail"
    | "link"
    | "img"
  >;

export const PlasmicFooterWrapper = function PlasmicFooterWrapperRoot<
  T extends PlasmicFooterWrapperRootProps
>(props: T & StrictProps<T, PlasmicFooterWrapperRootProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "root",
    descendantNames: [
      "root",
      "contactInfo",
      "linkedIn",
      "linkedin",
      "gitHub",
      "github",
      "gmail",
      "link",
      "img"
    ],

    internalArgPropNames: PlasmicFooterWrapper__ArgProps,
    internalVariantPropNames: PlasmicFooterWrapper__VariantProps
  });

  return PlasmicFooterWrapper__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "root"
  });
};

type PlasmicFooterWrapperContactInfoProps = PlasmicFooterWrapper__VariantsArgs &
  PlasmicFooterWrapper__ArgsType & {
    variants?: PlasmicFooterWrapper__VariantsArgs;
    args?: PlasmicFooterWrapper__ArgsType;
    overrides?: {
      contactInfo?: Flex<"div">;
      linkedIn?: Flex<"a">;
      linkedin?: Flex<"div">;
      gitHub?: Flex<"a">;
      github?: Flex<"div">;
      gmail?: Flex<"div">;
      link?: Flex<"a">;
      img?: Flex<"img">;
    };

    contactInfo?: Flex<"div">;
    linkedIn?: Flex<"a">;
    linkedin?: Flex<"div">;
    gitHub?: Flex<"a">;
    github?: Flex<"div">;
    gmail?: Flex<"div">;
    link?: Flex<"a">;
    img?: Flex<"img">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicFooterWrapper__VariantsArgs
    | keyof PlasmicFooterWrapper__ArgsType
    | "variants"
    | "args"
    | "contactInfo"
    | "linkedIn"
    | "linkedin"
    | "gitHub"
    | "github"
    | "gmail"
    | "link"
    | "img"
  >;

PlasmicFooterWrapper.contactInfo = function PlasmicFooterWrapperContactInfo<
  T extends PlasmicFooterWrapperContactInfoProps
>(props: T & StrictProps<T, PlasmicFooterWrapperContactInfoProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "contactInfo",
    descendantNames: [
      "contactInfo",
      "linkedIn",
      "linkedin",
      "gitHub",
      "github",
      "gmail",
      "link",
      "img"
    ],

    internalArgPropNames: PlasmicFooterWrapper__ArgProps,
    internalVariantPropNames: PlasmicFooterWrapper__VariantProps
  });

  return PlasmicFooterWrapper__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "contactInfo"
  });
};

type PlasmicFooterWrapperLinkedInProps = PlasmicFooterWrapper__VariantsArgs &
  PlasmicFooterWrapper__ArgsType & {
    variants?: PlasmicFooterWrapper__VariantsArgs;
    args?: PlasmicFooterWrapper__ArgsType;
    overrides?: {
      linkedIn?: Flex<"a">;
      linkedin?: Flex<"div">;
    };

    linkedIn?: Flex<"a">;
    linkedin?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"a">>,
    | keyof PlasmicFooterWrapper__VariantsArgs
    | keyof PlasmicFooterWrapper__ArgsType
    | "variants"
    | "args"
    | "linkedIn"
    | "linkedin"
  >;

PlasmicFooterWrapper.linkedIn = function PlasmicFooterWrapperLinkedIn<
  T extends PlasmicFooterWrapperLinkedInProps
>(props: T & StrictProps<T, PlasmicFooterWrapperLinkedInProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "linkedIn",
    descendantNames: ["linkedIn", "linkedin"],
    internalArgPropNames: PlasmicFooterWrapper__ArgProps,
    internalVariantPropNames: PlasmicFooterWrapper__VariantProps
  });

  return PlasmicFooterWrapper__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "linkedIn"
  });
};

type PlasmicFooterWrapperLinkedinProps = PlasmicFooterWrapper__VariantsArgs &
  PlasmicFooterWrapper__ArgsType & {
    variants?: PlasmicFooterWrapper__VariantsArgs;
    args?: PlasmicFooterWrapper__ArgsType;
    overrides?: {
      linkedin?: Flex<"div">;
    };

    linkedin?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicFooterWrapper__VariantsArgs
    | keyof PlasmicFooterWrapper__ArgsType
    | "variants"
    | "args"
    | "linkedin"
  >;

PlasmicFooterWrapper.linkedin = function PlasmicFooterWrapperLinkedin<
  T extends PlasmicFooterWrapperLinkedinProps
>(props: T & StrictProps<T, PlasmicFooterWrapperLinkedinProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "linkedin",
    descendantNames: ["linkedin"],
    internalArgPropNames: PlasmicFooterWrapper__ArgProps,
    internalVariantPropNames: PlasmicFooterWrapper__VariantProps
  });

  return PlasmicFooterWrapper__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "linkedin"
  });
};

type PlasmicFooterWrapperGitHubProps = PlasmicFooterWrapper__VariantsArgs &
  PlasmicFooterWrapper__ArgsType & {
    variants?: PlasmicFooterWrapper__VariantsArgs;
    args?: PlasmicFooterWrapper__ArgsType;
    overrides?: {
      gitHub?: Flex<"a">;
      github?: Flex<"div">;
    };

    gitHub?: Flex<"a">;
    github?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"a">>,
    | keyof PlasmicFooterWrapper__VariantsArgs
    | keyof PlasmicFooterWrapper__ArgsType
    | "variants"
    | "args"
    | "gitHub"
    | "github"
  >;

PlasmicFooterWrapper.gitHub = function PlasmicFooterWrapperGitHub<
  T extends PlasmicFooterWrapperGitHubProps
>(props: T & StrictProps<T, PlasmicFooterWrapperGitHubProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "gitHub",
    descendantNames: ["gitHub", "github"],
    internalArgPropNames: PlasmicFooterWrapper__ArgProps,
    internalVariantPropNames: PlasmicFooterWrapper__VariantProps
  });

  return PlasmicFooterWrapper__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "gitHub"
  });
};

type PlasmicFooterWrapperGithubProps = PlasmicFooterWrapper__VariantsArgs &
  PlasmicFooterWrapper__ArgsType & {
    variants?: PlasmicFooterWrapper__VariantsArgs;
    args?: PlasmicFooterWrapper__ArgsType;
    overrides?: {
      github?: Flex<"div">;
    };

    github?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicFooterWrapper__VariantsArgs
    | keyof PlasmicFooterWrapper__ArgsType
    | "variants"
    | "args"
    | "github"
  >;

PlasmicFooterWrapper.github = function PlasmicFooterWrapperGithub<
  T extends PlasmicFooterWrapperGithubProps
>(props: T & StrictProps<T, PlasmicFooterWrapperGithubProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "github",
    descendantNames: ["github"],
    internalArgPropNames: PlasmicFooterWrapper__ArgProps,
    internalVariantPropNames: PlasmicFooterWrapper__VariantProps
  });

  return PlasmicFooterWrapper__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "github"
  });
};

type PlasmicFooterWrapperGmailProps = PlasmicFooterWrapper__VariantsArgs &
  PlasmicFooterWrapper__ArgsType & {
    variants?: PlasmicFooterWrapper__VariantsArgs;
    args?: PlasmicFooterWrapper__ArgsType;
    overrides?: {
      gmail?: Flex<"div">;
      link?: Flex<"a">;
      img?: Flex<"img">;
    };

    gmail?: Flex<"div">;
    link?: Flex<"a">;
    img?: Flex<"img">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicFooterWrapper__VariantsArgs
    | keyof PlasmicFooterWrapper__ArgsType
    | "variants"
    | "args"
    | "gmail"
    | "link"
    | "img"
  >;

PlasmicFooterWrapper.gmail = function PlasmicFooterWrapperGmail<
  T extends PlasmicFooterWrapperGmailProps
>(props: T & StrictProps<T, PlasmicFooterWrapperGmailProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "gmail",
    descendantNames: ["gmail", "link", "img"],
    internalArgPropNames: PlasmicFooterWrapper__ArgProps,
    internalVariantPropNames: PlasmicFooterWrapper__VariantProps
  });

  return PlasmicFooterWrapper__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "gmail"
  });
};

type PlasmicFooterWrapperLinkProps = PlasmicFooterWrapper__VariantsArgs &
  PlasmicFooterWrapper__ArgsType & {
    variants?: PlasmicFooterWrapper__VariantsArgs;
    args?: PlasmicFooterWrapper__ArgsType;
    overrides?: {
      link?: Flex<"a">;
    };

    link?: Flex<"a">;
  } & Omit<
    Partial<React.ComponentProps<"a">>,
    | keyof PlasmicFooterWrapper__VariantsArgs
    | keyof PlasmicFooterWrapper__ArgsType
    | "variants"
    | "args"
    | "link"
  >;

PlasmicFooterWrapper.link = function PlasmicFooterWrapperLink<
  T extends PlasmicFooterWrapperLinkProps
>(props: T & StrictProps<T, PlasmicFooterWrapperLinkProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "link",
    descendantNames: ["link"],
    internalArgPropNames: PlasmicFooterWrapper__ArgProps,
    internalVariantPropNames: PlasmicFooterWrapper__VariantProps
  });

  return PlasmicFooterWrapper__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "link"
  });
};

type PlasmicFooterWrapperImgProps = PlasmicFooterWrapper__VariantsArgs &
  PlasmicFooterWrapper__ArgsType & {
    variants?: PlasmicFooterWrapper__VariantsArgs;
    args?: PlasmicFooterWrapper__ArgsType;
    overrides?: {
      img?: Flex<"img">;
    };

    img?: Flex<"img">;
  } & Omit<
    Partial<React.ComponentProps<"img">>,
    | keyof PlasmicFooterWrapper__VariantsArgs
    | keyof PlasmicFooterWrapper__ArgsType
    | "variants"
    | "args"
    | "img"
  >;

PlasmicFooterWrapper.img = function PlasmicFooterWrapperImg<
  T extends PlasmicFooterWrapperImgProps
>(props: T & StrictProps<T, PlasmicFooterWrapperImgProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "img",
    descendantNames: ["img"],
    internalArgPropNames: PlasmicFooterWrapper__ArgProps,
    internalVariantPropNames: PlasmicFooterWrapper__VariantProps
  });

  return PlasmicFooterWrapper__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "img"
  });
};

PlasmicFooterWrapper.createRenderer = () =>
  new PlasmicFooterWrapper__Renderer({}, {});

export default PlasmicFooterWrapper;
/* prettier-ignore-end */
