/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsx createPlasmicElementProxy */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eygJxeRspPrtKABTYb2Jd2
// Component: WoUevCP7iO
import * as React from "react";
import {
  hasVariant,
  classNames,
  Flex,
  wrapWithClassName,
  Renderer,
  NodeRenderer,
  createPlasmicElementProxy,
  makeFragment,
  PlasmicIcon,
  PlasmicSlot,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_brenorocha_dev.css"; // plasmic-import: eygJxeRspPrtKABTYb2Jd2/projectcss
import "./PlasmicWelcomeText.css"; // plasmic-import: WoUevCP7iO/css

export type PlasmicWelcomeText__VariantMembers = {};
export type PlasmicWelcomeText__VariantsArgs = {};
export const PlasmicWelcomeText__VariantProps = new Array<
  keyof PlasmicWelcomeText__VariantsArgs
>();

export type PlasmicWelcomeText__ArgsType = {};
export const PlasmicWelcomeText__ArgProps = new Array<
  keyof PlasmicWelcomeText__ArgsType
>();

export type PlasmicWelcomeText__OverridesType = {
  welcome?: Flex<"a">;
};

export interface DefaultWelcomeTextProps {
  className?: string;
}

function PlasmicWelcomeText__RenderFunc(props: {
  variants: PlasmicWelcomeText__VariantsArgs;
  args: PlasmicWelcomeText__ArgsType;
  overrides: PlasmicWelcomeText__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  const [isWelcomeHover, triggerWelcomeHoverProps] = useTrigger("useHover", {});
  const triggers = {
    hover_welcome: isWelcomeHover
  };

  return (
    <a
      data-plasmic-name={"welcome"}
      data-plasmic-override={overrides.welcome}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={
        classNames({
          "WelcomeText__welcome--__nXmUUsush5": triggers.hover_welcome,
          WelcomeText__welcome__nXmUU: true,
          "plasmic-default__a": true,
          "plasmic-default__all": true
        }) +
        " " +
        ("welcome" as const) +
        " __wab_text"
      }
      data-plasmic-trigger-props={[triggerWelcomeHoverProps]}
    >
      {triggers.hover_welcome
        ? "THE BEST PART OF LIFE IS BEING ALIVE\n\nENJOY THE JOURNEY!\nWELCOME"
        : "THE BEST PART OF LIFE IS BEING ALIVE"}
    </a>
  ) as React.ReactElement | null;
}

class PlasmicWelcomeText__Renderer extends Renderer<
  PlasmicWelcomeText__VariantsArgs,
  PlasmicWelcomeText__ArgsType,
  PlasmicWelcomeText__OverridesType,
  "welcome"
  > {
  constructor(
    variants: PlasmicWelcomeText__VariantsArgs,
    args: PlasmicWelcomeText__ArgsType
  ) {
    super(variants, args, PlasmicWelcomeText__RenderFunc, "welcome");
  }

  protected create(
    variants: PlasmicWelcomeText__VariantsArgs,
    args: PlasmicWelcomeText__ArgsType
  ) {
    return new PlasmicWelcomeText__Renderer(variants, args);
  }

  getInternalVariantProps(): (keyof PlasmicWelcomeText__VariantsArgs)[] {
    return PlasmicWelcomeText__VariantProps;
  }

  getInternalArgProps(): (keyof PlasmicWelcomeText__ArgsType)[] {
    return PlasmicWelcomeText__ArgProps;
  }

  forNode(
    name: "welcome"
  ): NodeRenderer<
    PlasmicWelcomeText__VariantsArgs,
    PlasmicWelcomeText__ArgsType,
    {
      welcome?: Flex<"a">;
    }
  >;

  forNode(name: keyof PlasmicWelcomeText__OverridesType) {
    return super.forNode(name);
  }
}

type PlasmicWelcomeTextWelcomeProps = PlasmicWelcomeText__VariantsArgs &
  PlasmicWelcomeText__ArgsType & {
    variants?: PlasmicWelcomeText__VariantsArgs;
    args?: PlasmicWelcomeText__ArgsType;
    overrides?: {
      welcome?: Flex<"a">;
    };

    welcome?: Flex<"a">;
  } & Omit<
    Partial<React.ComponentProps<"a">>,
    | keyof PlasmicWelcomeText__VariantsArgs
    | keyof PlasmicWelcomeText__ArgsType
    | "variants"
    | "args"
    | "welcome"
  >;

export const PlasmicWelcomeText = function PlasmicWelcomeTextWelcome<
  T extends PlasmicWelcomeTextWelcomeProps
>(props: T & StrictProps<T, PlasmicWelcomeTextWelcomeProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "welcome",
    descendantNames: ["welcome"],
    internalArgPropNames: PlasmicWelcomeText__ArgProps,
    internalVariantPropNames: PlasmicWelcomeText__VariantProps
  });

  return PlasmicWelcomeText__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "welcome"
  });
};

PlasmicWelcomeText.createRenderer = () =>
  new PlasmicWelcomeText__Renderer({}, {});

export default PlasmicWelcomeText;
/* prettier-ignore-end */
