/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsx createPlasmicElementProxy */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eygJxeRspPrtKABTYb2Jd2
// Component: Myj_maqtK6S
import * as React from "react";
import {
  hasVariant,
  classNames,
  Flex,
  wrapWithClassName,
  Renderer,
  NodeRenderer,
  createPlasmicElementProxy,
  makeFragment,
  PlasmicIcon,
  PlasmicSlot,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_brenorocha_dev.css"; // plasmic-import: eygJxeRspPrtKABTYb2Jd2/projectcss
import "./PlasmicSecondSection.css"; // plasmic-import: Myj_maqtK6S/css

export type PlasmicSecondSection__VariantMembers = {};
export type PlasmicSecondSection__VariantsArgs = {};
export const PlasmicSecondSection__VariantProps = new Array<
  keyof PlasmicSecondSection__VariantsArgs
>();

export type PlasmicSecondSection__ArgsType = {};
export const PlasmicSecondSection__ArgProps = new Array<
  keyof PlasmicSecondSection__ArgsType
>();

export type PlasmicSecondSection__OverridesType = {
  root?: Flex<"div">;
  webApp?: Flex<"div">;
  screenshotFrom202010060105201?: Flex<"div">;
  screenshotFrom202010060104151?: Flex<"div">;
  screenshotFrom202010060103171?: Flex<"div">;
  techs?: Flex<"div">;
  nodejs?: Flex<"div">;
  rectangle4?: Flex<"div">;
  javaScript?: Flex<"div">;
  rectangle42?: Flex<"div">;
  typeScript?: Flex<"div">;
  rectangle43?: Flex<"div">;
  reactjs?: Flex<"div">;
  rectangle44?: Flex<"div">;
};

export interface DefaultSecondSectionProps {
  className?: string;
}

function PlasmicSecondSection__RenderFunc(props: {
  variants: PlasmicSecondSection__VariantsArgs;
  args: PlasmicSecondSection__ArgsType;
  overrides: PlasmicSecondSection__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames({
        SecondSection__root__oII15: true,
        "plasmic-default__all": true,
        "plasmic-default__div": true
      })}
    >
      <div
        className={classNames({
          SecondSection__box__MjzCf: true,
          "plasmic-default__all": true,
          "plasmic-default__div": true
        })}
      >
        <a
          className={
            classNames({
              SecondSection__link__tz5Jb: true,
              "plasmic-default__a": true,
              "plasmic-default__all": true
            }) + " __wab_text"
          }
          href={"https://github.com/git-BR/the-movie-palace" as const}
        >
          {"AND FOR WEB"}
        </a>

        <div
          className={classNames({
            SecondSection__box__IFYMn: true,
            "plasmic-default__all": true,
            "plasmic-default__div": true
          })}
        >
          <div
            data-plasmic-name={"webApp"}
            data-plasmic-override={overrides.webApp}
            className={
              classNames({
                "SecondSection__webApp__-LdIM": true,
                "plasmic-default__all": true,
                "plasmic-default__div": true
              }) +
              " " +
              ("web-app" as const)
            }
          >
            <div
              data-plasmic-name={"screenshotFrom202010060105201"}
              data-plasmic-override={overrides.screenshotFrom202010060105201}
              className={
                classNames({
                  SecondSection__screenshotFrom202010060105201__1S8w6: true,
                  "plasmic-default__all": true,
                  "plasmic-default__div": true
                }) +
                " " +
                ("web-app-img3" as const)
              }
            ></div>

            <div
              data-plasmic-name={"screenshotFrom202010060104151"}
              data-plasmic-override={overrides.screenshotFrom202010060104151}
              className={
                classNames({
                  SecondSection__screenshotFrom202010060104151__cpsYr: true,
                  "plasmic-default__all": true,
                  "plasmic-default__div": true
                }) +
                " " +
                ("web-app-img2" as const)
              }
            ></div>

            <div
              data-plasmic-name={"screenshotFrom202010060103171"}
              data-plasmic-override={overrides.screenshotFrom202010060103171}
              className={
                classNames({
                  SecondSection__screenshotFrom202010060103171__oaRbp: true,
                  "plasmic-default__all": true,
                  "plasmic-default__div": true
                }) +
                " " +
                ("web-app-img1" as const)
              }
            ></div>
          </div>

          <div
            className={classNames({
              SecondSection__box__koGZt: true,
              "plasmic-default__all": true,
              "plasmic-default__div": true
            })}
          >
            <div
              className={
                classNames({
                  SecondSection__box__tRzuP: true,
                  "plasmic-default__all": true,
                  "plasmic-default__div": true
                }) + " __wab_text"
              }
            >
              {"CUTTING-EDGE\nTECHNOLOGY"}
            </div>

            <div
              className={classNames({
                SecondSection__box__R3wTE: true,
                "plasmic-default__all": true,
                "plasmic-default__div": true
              })}
            >
              <div
                data-plasmic-name={"techs"}
                data-plasmic-override={overrides.techs}
                className={
                  classNames({
                    SecondSection__techs__xkgCt: true,
                    "plasmic-default__all": true,
                    "plasmic-default__div": true
                  }) +
                  " " +
                  ("techs" as const)
                }
              >
                <div
                  data-plasmic-name={"nodejs"}
                  data-plasmic-override={overrides.nodejs}
                  className={
                    classNames({
                      SecondSection__nodejs__TxIlP: true,
                      "plasmic-default__all": true,
                      "plasmic-default__div": true
                    }) +
                    " " +
                    ("react" as const)
                  }
                >
                  <div
                    data-plasmic-name={"rectangle4"}
                    data-plasmic-override={overrides.rectangle4}
                    className={classNames({
                      SecondSection__rectangle4__06Npq: true,
                      "plasmic-default__all": true,
                      "plasmic-default__div": true
                    })}
                  >
                    <a
                      className={
                        classNames({
                          "SecondSection__link__ZD-Uj": true,
                          "plasmic-default__a": true,
                          "plasmic-default__all": true
                        }) + " __wab_text"
                      }
                      href={"https://nodejs.org/en/" as const}
                    >
                      {"NODE"}
                    </a>
                  </div>
                </div>

                <div
                  data-plasmic-name={"javaScript"}
                  data-plasmic-override={overrides.javaScript}
                  className={
                    classNames({
                      SecondSection__javaScript__3qtka: true,
                      "plasmic-default__all": true,
                      "plasmic-default__div": true
                    }) +
                    " " +
                    ("javascript" as const)
                  }
                >
                  <div
                    data-plasmic-name={"rectangle42"}
                    data-plasmic-override={overrides.rectangle42}
                    className={classNames({
                      SecondSection__rectangle42__Z9ahP: true,
                      "plasmic-default__all": true,
                      "plasmic-default__div": true
                    })}
                  >
                    <a
                      className={
                        classNames({
                          SecondSection__link__fDTd5: true,
                          "plasmic-default__a": true,
                          "plasmic-default__all": true
                        }) + " __wab_text"
                      }
                      href={
                        "https://developer.mozilla.org/en-US/docs/Web/JavaScript" as const
                      }
                    >
                      {"JAVASCRIPT"}
                    </a>
                  </div>
                </div>

                <div
                  data-plasmic-name={"typeScript"}
                  data-plasmic-override={overrides.typeScript}
                  className={
                    classNames({
                      SecondSection__typeScript__R5y_k: true,
                      "plasmic-default__all": true,
                      "plasmic-default__div": true
                    }) +
                    " " +
                    ("typescript" as const)
                  }
                >
                  <div
                    data-plasmic-name={"rectangle43"}
                    data-plasmic-override={overrides.rectangle43}
                    className={classNames({
                      SecondSection__rectangle43__nUYGI: true,
                      "plasmic-default__all": true,
                      "plasmic-default__div": true
                    })}
                  >
                    <a
                      className={
                        classNames({
                          SecondSection__link__JFdN9: true,
                          "plasmic-default__a": true,
                          "plasmic-default__all": true
                        }) + " __wab_text"
                      }
                      href={"https://www.typescriptlang.org/" as const}
                    >
                      {"TYPESCRIPT"}
                    </a>
                  </div>
                </div>

                <div
                  data-plasmic-name={"reactjs"}
                  data-plasmic-override={overrides.reactjs}
                  className={
                    classNames({
                      SecondSection__reactjs__IOSz8: true,
                      "plasmic-default__all": true,
                      "plasmic-default__div": true
                    }) +
                    " " +
                    ("node" as const)
                  }
                >
                  <div
                    data-plasmic-name={"rectangle44"}
                    data-plasmic-override={overrides.rectangle44}
                    className={classNames({
                      SecondSection__rectangle44__DR4wb: true,
                      "plasmic-default__all": true,
                      "plasmic-default__div": true
                    })}
                  >
                    <a
                      className={
                        classNames({
                          SecondSection__link__Hjfy8: true,
                          "plasmic-default__a": true,
                          "plasmic-default__all": true
                        }) + " __wab_text"
                      }
                      href={"https://reactjs.org/" as const}
                    >
                      {"REACT"}
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div
          className={classNames({
            "SecondSection__box__Zr-_p": true,
            "plasmic-default__all": true,
            "plasmic-default__div": true
          })}
        >
          <div
            className={
              classNames({
                SecondSection__box__i41kD: true,
                "plasmic-default__all": true,
                "plasmic-default__div": true
              }) + " __wab_text"
            }
          >
            {"powered by the Internet and open-source community "}
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

class PlasmicSecondSection__Renderer extends Renderer<
  PlasmicSecondSection__VariantsArgs,
  PlasmicSecondSection__ArgsType,
  PlasmicSecondSection__OverridesType,
  "root"
> {
  constructor(
    variants: PlasmicSecondSection__VariantsArgs,
    args: PlasmicSecondSection__ArgsType
  ) {
    super(variants, args, PlasmicSecondSection__RenderFunc, "root");
  }

  protected create(
    variants: PlasmicSecondSection__VariantsArgs,
    args: PlasmicSecondSection__ArgsType
  ) {
    return new PlasmicSecondSection__Renderer(variants, args);
  }

  getInternalVariantProps(): (keyof PlasmicSecondSection__VariantsArgs)[] {
    return PlasmicSecondSection__VariantProps;
  }

  getInternalArgProps(): (keyof PlasmicSecondSection__ArgsType)[] {
    return PlasmicSecondSection__ArgProps;
  }

  forNode(
    name: "rectangle44"
  ): NodeRenderer<
    PlasmicSecondSection__VariantsArgs,
    PlasmicSecondSection__ArgsType,
    {
      rectangle44?: Flex<"div">;
    }
  >;

  forNode(
    name: "reactjs"
  ): NodeRenderer<
    PlasmicSecondSection__VariantsArgs,
    PlasmicSecondSection__ArgsType,
    {
      reactjs?: Flex<"div">;
      rectangle44?: Flex<"div">;
    }
  >;

  forNode(
    name: "rectangle43"
  ): NodeRenderer<
    PlasmicSecondSection__VariantsArgs,
    PlasmicSecondSection__ArgsType,
    {
      rectangle43?: Flex<"div">;
    }
  >;

  forNode(
    name: "typeScript"
  ): NodeRenderer<
    PlasmicSecondSection__VariantsArgs,
    PlasmicSecondSection__ArgsType,
    {
      typeScript?: Flex<"div">;
      rectangle43?: Flex<"div">;
    }
  >;

  forNode(
    name: "rectangle42"
  ): NodeRenderer<
    PlasmicSecondSection__VariantsArgs,
    PlasmicSecondSection__ArgsType,
    {
      rectangle42?: Flex<"div">;
    }
  >;

  forNode(
    name: "javaScript"
  ): NodeRenderer<
    PlasmicSecondSection__VariantsArgs,
    PlasmicSecondSection__ArgsType,
    {
      javaScript?: Flex<"div">;
      rectangle42?: Flex<"div">;
    }
  >;

  forNode(
    name: "rectangle4"
  ): NodeRenderer<
    PlasmicSecondSection__VariantsArgs,
    PlasmicSecondSection__ArgsType,
    {
      rectangle4?: Flex<"div">;
    }
  >;

  forNode(
    name: "nodejs"
  ): NodeRenderer<
    PlasmicSecondSection__VariantsArgs,
    PlasmicSecondSection__ArgsType,
    {
      nodejs?: Flex<"div">;
      rectangle4?: Flex<"div">;
    }
  >;

  forNode(
    name: "techs"
  ): NodeRenderer<
    PlasmicSecondSection__VariantsArgs,
    PlasmicSecondSection__ArgsType,
    {
      techs?: Flex<"div">;
      nodejs?: Flex<"div">;
      rectangle4?: Flex<"div">;
      javaScript?: Flex<"div">;
      rectangle42?: Flex<"div">;
      typeScript?: Flex<"div">;
      rectangle43?: Flex<"div">;
      reactjs?: Flex<"div">;
      rectangle44?: Flex<"div">;
    }
  >;

  forNode(
    name: "screenshotFrom202010060103171"
  ): NodeRenderer<
    PlasmicSecondSection__VariantsArgs,
    PlasmicSecondSection__ArgsType,
    {
      screenshotFrom202010060103171?: Flex<"div">;
    }
  >;

  forNode(
    name: "screenshotFrom202010060104151"
  ): NodeRenderer<
    PlasmicSecondSection__VariantsArgs,
    PlasmicSecondSection__ArgsType,
    {
      screenshotFrom202010060104151?: Flex<"div">;
    }
  >;

  forNode(
    name: "screenshotFrom202010060105201"
  ): NodeRenderer<
    PlasmicSecondSection__VariantsArgs,
    PlasmicSecondSection__ArgsType,
    {
      screenshotFrom202010060105201?: Flex<"div">;
    }
  >;

  forNode(
    name: "webApp"
  ): NodeRenderer<
    PlasmicSecondSection__VariantsArgs,
    PlasmicSecondSection__ArgsType,
    {
      webApp?: Flex<"div">;
      screenshotFrom202010060105201?: Flex<"div">;
      screenshotFrom202010060104151?: Flex<"div">;
      screenshotFrom202010060103171?: Flex<"div">;
    }
  >;

  forNode(
    name: "root"
  ): NodeRenderer<
    PlasmicSecondSection__VariantsArgs,
    PlasmicSecondSection__ArgsType,
    {
      root?: Flex<"div">;
      webApp?: Flex<"div">;
      screenshotFrom202010060105201?: Flex<"div">;
      screenshotFrom202010060104151?: Flex<"div">;
      screenshotFrom202010060103171?: Flex<"div">;
      techs?: Flex<"div">;
      nodejs?: Flex<"div">;
      rectangle4?: Flex<"div">;
      javaScript?: Flex<"div">;
      rectangle42?: Flex<"div">;
      typeScript?: Flex<"div">;
      rectangle43?: Flex<"div">;
      reactjs?: Flex<"div">;
      rectangle44?: Flex<"div">;
    }
  >;

  forNode(name: keyof PlasmicSecondSection__OverridesType) {
    return super.forNode(name);
  }
}

type PlasmicSecondSectionRootProps = PlasmicSecondSection__VariantsArgs &
  PlasmicSecondSection__ArgsType & {
    variants?: PlasmicSecondSection__VariantsArgs;
    args?: PlasmicSecondSection__ArgsType;
    overrides?: {
      root?: Flex<"div">;
      webApp?: Flex<"div">;
      screenshotFrom202010060105201?: Flex<"div">;
      screenshotFrom202010060104151?: Flex<"div">;
      screenshotFrom202010060103171?: Flex<"div">;
      techs?: Flex<"div">;
      nodejs?: Flex<"div">;
      rectangle4?: Flex<"div">;
      javaScript?: Flex<"div">;
      rectangle42?: Flex<"div">;
      typeScript?: Flex<"div">;
      rectangle43?: Flex<"div">;
      reactjs?: Flex<"div">;
      rectangle44?: Flex<"div">;
    };

    root?: Flex<"div">;
    webApp?: Flex<"div">;
    screenshotFrom202010060105201?: Flex<"div">;
    screenshotFrom202010060104151?: Flex<"div">;
    screenshotFrom202010060103171?: Flex<"div">;
    techs?: Flex<"div">;
    nodejs?: Flex<"div">;
    rectangle4?: Flex<"div">;
    javaScript?: Flex<"div">;
    rectangle42?: Flex<"div">;
    typeScript?: Flex<"div">;
    rectangle43?: Flex<"div">;
    reactjs?: Flex<"div">;
    rectangle44?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicSecondSection__VariantsArgs
    | keyof PlasmicSecondSection__ArgsType
    | "variants"
    | "args"
    | "root"
    | "webApp"
    | "screenshotFrom202010060105201"
    | "screenshotFrom202010060104151"
    | "screenshotFrom202010060103171"
    | "techs"
    | "nodejs"
    | "rectangle4"
    | "javaScript"
    | "rectangle42"
    | "typeScript"
    | "rectangle43"
    | "reactjs"
    | "rectangle44"
  >;

export const PlasmicSecondSection = function PlasmicSecondSectionRoot<
  T extends PlasmicSecondSectionRootProps
>(props: T & StrictProps<T, PlasmicSecondSectionRootProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "root",
    descendantNames: [
      "root",
      "webApp",
      "screenshotFrom202010060105201",
      "screenshotFrom202010060104151",
      "screenshotFrom202010060103171",
      "techs",
      "nodejs",
      "rectangle4",
      "javaScript",
      "rectangle42",
      "typeScript",
      "rectangle43",
      "reactjs",
      "rectangle44"
    ],

    internalArgPropNames: PlasmicSecondSection__ArgProps,
    internalVariantPropNames: PlasmicSecondSection__VariantProps
  });

  return PlasmicSecondSection__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "root"
  });
};

type PlasmicSecondSectionWebAppProps = PlasmicSecondSection__VariantsArgs &
  PlasmicSecondSection__ArgsType & {
    variants?: PlasmicSecondSection__VariantsArgs;
    args?: PlasmicSecondSection__ArgsType;
    overrides?: {
      webApp?: Flex<"div">;
      screenshotFrom202010060105201?: Flex<"div">;
      screenshotFrom202010060104151?: Flex<"div">;
      screenshotFrom202010060103171?: Flex<"div">;
    };

    webApp?: Flex<"div">;
    screenshotFrom202010060105201?: Flex<"div">;
    screenshotFrom202010060104151?: Flex<"div">;
    screenshotFrom202010060103171?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicSecondSection__VariantsArgs
    | keyof PlasmicSecondSection__ArgsType
    | "variants"
    | "args"
    | "webApp"
    | "screenshotFrom202010060105201"
    | "screenshotFrom202010060104151"
    | "screenshotFrom202010060103171"
  >;

PlasmicSecondSection.webApp = function PlasmicSecondSectionWebApp<
  T extends PlasmicSecondSectionWebAppProps
>(props: T & StrictProps<T, PlasmicSecondSectionWebAppProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "webApp",
    descendantNames: [
      "webApp",
      "screenshotFrom202010060105201",
      "screenshotFrom202010060104151",
      "screenshotFrom202010060103171"
    ],

    internalArgPropNames: PlasmicSecondSection__ArgProps,
    internalVariantPropNames: PlasmicSecondSection__VariantProps
  });

  return PlasmicSecondSection__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "webApp"
  });
};

type PlasmicSecondSectionScreenshotFrom202010060105201Props = PlasmicSecondSection__VariantsArgs &
  PlasmicSecondSection__ArgsType & {
    variants?: PlasmicSecondSection__VariantsArgs;
    args?: PlasmicSecondSection__ArgsType;
    overrides?: {
      screenshotFrom202010060105201?: Flex<"div">;
    };

    screenshotFrom202010060105201?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicSecondSection__VariantsArgs
    | keyof PlasmicSecondSection__ArgsType
    | "variants"
    | "args"
    | "screenshotFrom202010060105201"
  >;

PlasmicSecondSection.screenshotFrom202010060105201 = function PlasmicSecondSectionScreenshotFrom202010060105201<
  T extends PlasmicSecondSectionScreenshotFrom202010060105201Props
>(
  props: T &
    StrictProps<T, PlasmicSecondSectionScreenshotFrom202010060105201Props>
) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "screenshotFrom202010060105201",
    descendantNames: ["screenshotFrom202010060105201"],
    internalArgPropNames: PlasmicSecondSection__ArgProps,
    internalVariantPropNames: PlasmicSecondSection__VariantProps
  });

  return PlasmicSecondSection__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "screenshotFrom202010060105201"
  });
};

type PlasmicSecondSectionScreenshotFrom202010060104151Props = PlasmicSecondSection__VariantsArgs &
  PlasmicSecondSection__ArgsType & {
    variants?: PlasmicSecondSection__VariantsArgs;
    args?: PlasmicSecondSection__ArgsType;
    overrides?: {
      screenshotFrom202010060104151?: Flex<"div">;
    };

    screenshotFrom202010060104151?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicSecondSection__VariantsArgs
    | keyof PlasmicSecondSection__ArgsType
    | "variants"
    | "args"
    | "screenshotFrom202010060104151"
  >;

PlasmicSecondSection.screenshotFrom202010060104151 = function PlasmicSecondSectionScreenshotFrom202010060104151<
  T extends PlasmicSecondSectionScreenshotFrom202010060104151Props
>(
  props: T &
    StrictProps<T, PlasmicSecondSectionScreenshotFrom202010060104151Props>
) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "screenshotFrom202010060104151",
    descendantNames: ["screenshotFrom202010060104151"],
    internalArgPropNames: PlasmicSecondSection__ArgProps,
    internalVariantPropNames: PlasmicSecondSection__VariantProps
  });

  return PlasmicSecondSection__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "screenshotFrom202010060104151"
  });
};

type PlasmicSecondSectionScreenshotFrom202010060103171Props = PlasmicSecondSection__VariantsArgs &
  PlasmicSecondSection__ArgsType & {
    variants?: PlasmicSecondSection__VariantsArgs;
    args?: PlasmicSecondSection__ArgsType;
    overrides?: {
      screenshotFrom202010060103171?: Flex<"div">;
    };

    screenshotFrom202010060103171?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicSecondSection__VariantsArgs
    | keyof PlasmicSecondSection__ArgsType
    | "variants"
    | "args"
    | "screenshotFrom202010060103171"
  >;

PlasmicSecondSection.screenshotFrom202010060103171 = function PlasmicSecondSectionScreenshotFrom202010060103171<
  T extends PlasmicSecondSectionScreenshotFrom202010060103171Props
>(
  props: T &
    StrictProps<T, PlasmicSecondSectionScreenshotFrom202010060103171Props>
) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "screenshotFrom202010060103171",
    descendantNames: ["screenshotFrom202010060103171"],
    internalArgPropNames: PlasmicSecondSection__ArgProps,
    internalVariantPropNames: PlasmicSecondSection__VariantProps
  });

  return PlasmicSecondSection__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "screenshotFrom202010060103171"
  });
};

type PlasmicSecondSectionTechsProps = PlasmicSecondSection__VariantsArgs &
  PlasmicSecondSection__ArgsType & {
    variants?: PlasmicSecondSection__VariantsArgs;
    args?: PlasmicSecondSection__ArgsType;
    overrides?: {
      techs?: Flex<"div">;
      nodejs?: Flex<"div">;
      rectangle4?: Flex<"div">;
      javaScript?: Flex<"div">;
      rectangle42?: Flex<"div">;
      typeScript?: Flex<"div">;
      rectangle43?: Flex<"div">;
      reactjs?: Flex<"div">;
      rectangle44?: Flex<"div">;
    };

    techs?: Flex<"div">;
    nodejs?: Flex<"div">;
    rectangle4?: Flex<"div">;
    javaScript?: Flex<"div">;
    rectangle42?: Flex<"div">;
    typeScript?: Flex<"div">;
    rectangle43?: Flex<"div">;
    reactjs?: Flex<"div">;
    rectangle44?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicSecondSection__VariantsArgs
    | keyof PlasmicSecondSection__ArgsType
    | "variants"
    | "args"
    | "techs"
    | "nodejs"
    | "rectangle4"
    | "javaScript"
    | "rectangle42"
    | "typeScript"
    | "rectangle43"
    | "reactjs"
    | "rectangle44"
  >;

PlasmicSecondSection.techs = function PlasmicSecondSectionTechs<
  T extends PlasmicSecondSectionTechsProps
>(props: T & StrictProps<T, PlasmicSecondSectionTechsProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "techs",
    descendantNames: [
      "techs",
      "nodejs",
      "rectangle4",
      "javaScript",
      "rectangle42",
      "typeScript",
      "rectangle43",
      "reactjs",
      "rectangle44"
    ],

    internalArgPropNames: PlasmicSecondSection__ArgProps,
    internalVariantPropNames: PlasmicSecondSection__VariantProps
  });

  return PlasmicSecondSection__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "techs"
  });
};

type PlasmicSecondSectionNodejsProps = PlasmicSecondSection__VariantsArgs &
  PlasmicSecondSection__ArgsType & {
    variants?: PlasmicSecondSection__VariantsArgs;
    args?: PlasmicSecondSection__ArgsType;
    overrides?: {
      nodejs?: Flex<"div">;
      rectangle4?: Flex<"div">;
    };

    nodejs?: Flex<"div">;
    rectangle4?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicSecondSection__VariantsArgs
    | keyof PlasmicSecondSection__ArgsType
    | "variants"
    | "args"
    | "nodejs"
    | "rectangle4"
  >;

PlasmicSecondSection.nodejs = function PlasmicSecondSectionNodejs<
  T extends PlasmicSecondSectionNodejsProps
>(props: T & StrictProps<T, PlasmicSecondSectionNodejsProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "nodejs",
    descendantNames: ["nodejs", "rectangle4"],
    internalArgPropNames: PlasmicSecondSection__ArgProps,
    internalVariantPropNames: PlasmicSecondSection__VariantProps
  });

  return PlasmicSecondSection__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "nodejs"
  });
};

type PlasmicSecondSectionRectangle4Props = PlasmicSecondSection__VariantsArgs &
  PlasmicSecondSection__ArgsType & {
    variants?: PlasmicSecondSection__VariantsArgs;
    args?: PlasmicSecondSection__ArgsType;
    overrides?: {
      rectangle4?: Flex<"div">;
    };

    rectangle4?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicSecondSection__VariantsArgs
    | keyof PlasmicSecondSection__ArgsType
    | "variants"
    | "args"
    | "rectangle4"
  >;

PlasmicSecondSection.rectangle4 = function PlasmicSecondSectionRectangle4<
  T extends PlasmicSecondSectionRectangle4Props
>(props: T & StrictProps<T, PlasmicSecondSectionRectangle4Props>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "rectangle4",
    descendantNames: ["rectangle4"],
    internalArgPropNames: PlasmicSecondSection__ArgProps,
    internalVariantPropNames: PlasmicSecondSection__VariantProps
  });

  return PlasmicSecondSection__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "rectangle4"
  });
};

type PlasmicSecondSectionJavaScriptProps = PlasmicSecondSection__VariantsArgs &
  PlasmicSecondSection__ArgsType & {
    variants?: PlasmicSecondSection__VariantsArgs;
    args?: PlasmicSecondSection__ArgsType;
    overrides?: {
      javaScript?: Flex<"div">;
      rectangle42?: Flex<"div">;
    };

    javaScript?: Flex<"div">;
    rectangle42?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicSecondSection__VariantsArgs
    | keyof PlasmicSecondSection__ArgsType
    | "variants"
    | "args"
    | "javaScript"
    | "rectangle42"
  >;

PlasmicSecondSection.javaScript = function PlasmicSecondSectionJavaScript<
  T extends PlasmicSecondSectionJavaScriptProps
>(props: T & StrictProps<T, PlasmicSecondSectionJavaScriptProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "javaScript",
    descendantNames: ["javaScript", "rectangle42"],
    internalArgPropNames: PlasmicSecondSection__ArgProps,
    internalVariantPropNames: PlasmicSecondSection__VariantProps
  });

  return PlasmicSecondSection__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "javaScript"
  });
};

type PlasmicSecondSectionRectangle42Props = PlasmicSecondSection__VariantsArgs &
  PlasmicSecondSection__ArgsType & {
    variants?: PlasmicSecondSection__VariantsArgs;
    args?: PlasmicSecondSection__ArgsType;
    overrides?: {
      rectangle42?: Flex<"div">;
    };

    rectangle42?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicSecondSection__VariantsArgs
    | keyof PlasmicSecondSection__ArgsType
    | "variants"
    | "args"
    | "rectangle42"
  >;

PlasmicSecondSection.rectangle42 = function PlasmicSecondSectionRectangle42<
  T extends PlasmicSecondSectionRectangle42Props
>(props: T & StrictProps<T, PlasmicSecondSectionRectangle42Props>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "rectangle42",
    descendantNames: ["rectangle42"],
    internalArgPropNames: PlasmicSecondSection__ArgProps,
    internalVariantPropNames: PlasmicSecondSection__VariantProps
  });

  return PlasmicSecondSection__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "rectangle42"
  });
};

type PlasmicSecondSectionTypeScriptProps = PlasmicSecondSection__VariantsArgs &
  PlasmicSecondSection__ArgsType & {
    variants?: PlasmicSecondSection__VariantsArgs;
    args?: PlasmicSecondSection__ArgsType;
    overrides?: {
      typeScript?: Flex<"div">;
      rectangle43?: Flex<"div">;
    };

    typeScript?: Flex<"div">;
    rectangle43?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicSecondSection__VariantsArgs
    | keyof PlasmicSecondSection__ArgsType
    | "variants"
    | "args"
    | "typeScript"
    | "rectangle43"
  >;

PlasmicSecondSection.typeScript = function PlasmicSecondSectionTypeScript<
  T extends PlasmicSecondSectionTypeScriptProps
>(props: T & StrictProps<T, PlasmicSecondSectionTypeScriptProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "typeScript",
    descendantNames: ["typeScript", "rectangle43"],
    internalArgPropNames: PlasmicSecondSection__ArgProps,
    internalVariantPropNames: PlasmicSecondSection__VariantProps
  });

  return PlasmicSecondSection__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "typeScript"
  });
};

type PlasmicSecondSectionRectangle43Props = PlasmicSecondSection__VariantsArgs &
  PlasmicSecondSection__ArgsType & {
    variants?: PlasmicSecondSection__VariantsArgs;
    args?: PlasmicSecondSection__ArgsType;
    overrides?: {
      rectangle43?: Flex<"div">;
    };

    rectangle43?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicSecondSection__VariantsArgs
    | keyof PlasmicSecondSection__ArgsType
    | "variants"
    | "args"
    | "rectangle43"
  >;

PlasmicSecondSection.rectangle43 = function PlasmicSecondSectionRectangle43<
  T extends PlasmicSecondSectionRectangle43Props
>(props: T & StrictProps<T, PlasmicSecondSectionRectangle43Props>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "rectangle43",
    descendantNames: ["rectangle43"],
    internalArgPropNames: PlasmicSecondSection__ArgProps,
    internalVariantPropNames: PlasmicSecondSection__VariantProps
  });

  return PlasmicSecondSection__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "rectangle43"
  });
};

type PlasmicSecondSectionReactjsProps = PlasmicSecondSection__VariantsArgs &
  PlasmicSecondSection__ArgsType & {
    variants?: PlasmicSecondSection__VariantsArgs;
    args?: PlasmicSecondSection__ArgsType;
    overrides?: {
      reactjs?: Flex<"div">;
      rectangle44?: Flex<"div">;
    };

    reactjs?: Flex<"div">;
    rectangle44?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicSecondSection__VariantsArgs
    | keyof PlasmicSecondSection__ArgsType
    | "variants"
    | "args"
    | "reactjs"
    | "rectangle44"
  >;

PlasmicSecondSection.reactjs = function PlasmicSecondSectionReactjs<
  T extends PlasmicSecondSectionReactjsProps
>(props: T & StrictProps<T, PlasmicSecondSectionReactjsProps>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "reactjs",
    descendantNames: ["reactjs", "rectangle44"],
    internalArgPropNames: PlasmicSecondSection__ArgProps,
    internalVariantPropNames: PlasmicSecondSection__VariantProps
  });

  return PlasmicSecondSection__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "reactjs"
  });
};

type PlasmicSecondSectionRectangle44Props = PlasmicSecondSection__VariantsArgs &
  PlasmicSecondSection__ArgsType & {
    variants?: PlasmicSecondSection__VariantsArgs;
    args?: PlasmicSecondSection__ArgsType;
    overrides?: {
      rectangle44?: Flex<"div">;
    };

    rectangle44?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicSecondSection__VariantsArgs
    | keyof PlasmicSecondSection__ArgsType
    | "variants"
    | "args"
    | "rectangle44"
  >;

PlasmicSecondSection.rectangle44 = function PlasmicSecondSectionRectangle44<
  T extends PlasmicSecondSectionRectangle44Props
>(props: T & StrictProps<T, PlasmicSecondSectionRectangle44Props>) {
  const { variants, args, overrides } = deriveRenderOpts(props, {
    name: "rectangle44",
    descendantNames: ["rectangle44"],
    internalArgPropNames: PlasmicSecondSection__ArgProps,
    internalVariantPropNames: PlasmicSecondSection__VariantProps
  });

  return PlasmicSecondSection__RenderFunc({
    variants,
    args,
    overrides,
    forNode: "rectangle44"
  });
};

PlasmicSecondSection.createRenderer = () =>
  new PlasmicSecondSection__Renderer({}, {});

export default PlasmicSecondSection;
/* prettier-ignore-end */
